# Generated by Django 2.1.2 on 2019-01-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_page_url_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='cover',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
