# Generated by Django 2.1.2 on 2018-10-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='timedtsmp',
            new_name='timestamp',
        ),
    ]
